package Modelo;
/**
 * 
 * @author Guill
 *
 */
public enum TipoEnvio {LOGIN,INFO,
	JUGADOR,MENU1,
	MENU2,NUMERO1,
	NUMERO2,INICIARPARTIDA,
    LOGINOK,LOGINNUEVO,LOGINERROR,
    LOGINYACONECTADO,ACTIVOS,RANKING,
    PARTACTIVAS,PARTFINALIZADAS,
    ESPERARETO,LANZARETO,ACEPTARETO,
    NOACEPTARETO,START,END,JUGADA,RECARGAR};
