package Vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import Controlador.Cliente;
import Modelo.Envio;
import Modelo.Partida;
import Modelo.TipoJugada;

/**
 * Interfaz con la que interactua el cliente para jugar
 * @author Guill
 *
 */
public class InterfazGraficaCliente extends javax.swing.JFrame implements Serializable {
    private Timer timer;
    private int contador;
    private String nombre;
    private Partida partida;
    private Controlador.Cliente cliente; 
    private Envio m;
    /**
     * Creates new form InterfazGraficaCliente
     */
    public InterfazGraficaCliente(Partida partida,Cliente c){
      
            initComponents();
            this.partida = partida;
            this.cliente = c;
            setTitle("Partida "+partida.getIdPartida());
            
            lblTu.setText(c.getJugador().getNombre());
            
            actualizarInterfaz();
    
    }

    public Partida getPartida() {
        return partida;
    }

    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    
    public void actualizarInterfaz(){
       
        lblGanadas.setText("Rondas ganadas: "+partida.getRondasGanadasJ1());
        lblRestantes.setText("Rondas restantes: "+partida.getRondasRestantes());
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    private void initComponents() {

        btnPiedra1 = new javax.swing.JButton();
        btnPiedra1.setFont(new Font("Monospaced", Font.PLAIN, 13));
        btnPapel1 = new javax.swing.JButton();
        btnPapel1.setFont(new Font("Monospaced", Font.PLAIN, 13));
        btnTijera1 = new javax.swing.JButton();
        btnTijera1.setFont(new Font("Monospaced", Font.PLAIN, 13));
        lblTu = new javax.swing.JLabel();
        lblTuContrincante = new javax.swing.JLabel();
        lblTuContrincante.setToolTipText("");
        lblGanadas = new javax.swing.JLabel();
        lblGanadas.setToolTipText("");
        lblRestantes = new javax.swing.JLabel();
        lblRestantes.setIcon(null);
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piedra, papel y tijera");

        btnPiedra1.setText("Piedra");
        btnPiedra1.setName("Piedra 1"); 
        btnPiedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedra1ActionPerformed(evt);
            }
        });

        btnPapel1.setText("Papel");
        btnPapel1.setName("Papel 1"); 
        btnPapel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapel1ActionPerformed(evt);
            }
        });

        btnTijera1.setText("Tijera");
        btnTijera1.setName("Tijera 1"); 
        btnTijera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijera1ActionPerformed(evt);
            }
        });

        lblTu.setFont(new Font("Monospaced", Font.BOLD, 20)); 
        lblTu.setText("Tú");

        lblTuContrincante.setFont(new Font("Monospaced", Font.PLAIN, 13)); 
        lblTuContrincante.setForeground(Color.BLACK);
        lblTuContrincante.setText("El rival ha elejido:");

        lblGanadas.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        lblGanadas.setForeground(Color.BLUE);
        lblGanadas.setText("Rondas ganadas: ");

        lblRestantes.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        lblRestantes.setForeground(Color.BLUE);
        lblRestantes.setText("Rondas restantes:");
        lblRestantes.setToolTipText("");

       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(83, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(9)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnTijera1)
        						.addComponent(btnPapel1)
        						.addComponent(btnPiedra1)))
        				.addComponent(lblTu))
        			.addGap(74)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblGanadas)
        				.addComponent(lblTuContrincante)
        				.addComponent(lblRestantes))
        			.addGap(81))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(26)
        			.addComponent(lblTu)
        			.addGap(35)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnPiedra1)
        				.addComponent(lblTuContrincante))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(btnPapel1)
        					.addGap(34)
        					.addComponent(btnTijera1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(69)
        					.addComponent(lblGanadas)
        					.addGap(18)
        					.addComponent(lblRestantes)))
        			.addContainerGap(105, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }

    private void btnPiedra1ActionPerformed(java.awt.event.ActionEvent evt) {
        pulsarBoton(btnPiedra1);
    }

    private void btnPapel1ActionPerformed(java.awt.event.ActionEvent evt) {
        pulsarBoton(btnPapel1);
    }

    private void btnTijera1ActionPerformed(java.awt.event.ActionEvent evt) {
        pulsarBoton(btnTijera1);
    }

    private void pulsarBoton(javax.swing.JButton boton){
        cambiarColor(boton, Color.red);
        
        
        
        cliente.jugadaRealizada(TipoJugada.valueOf(boton.getText().toUpperCase()),partida);
        timer.stop();
        
        
        resetearBotones();
        resetearTiempo();
        startTiempo();
    }
    public void cambiarColor(javax.swing.JButton boton, Color color){
        boton.setBackground(color);
        
    }
    public void resetearBotones(){        
        btnPiedra1.setBackground(Color.lightGray);
        btnPapel1.setBackground(Color.lightGray);
        btnTijera1.setBackground(Color.lightGray);
    }
    
    public void resetearTiempo(){
        contador=5;
       
    }
    
    public void startTiempo(){
        timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    private javax.swing.JButton btnPapel1;
    private javax.swing.JButton btnPiedra1;
    private javax.swing.JButton btnTijera1;
    private javax.swing.JLabel lblGanadas;
    private javax.swing.JLabel lblRestantes;
   
    private javax.swing.JLabel lblTu;
    private javax.swing.JLabel lblTuContrincante;

   
}
